### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by UdoKifferbrehl** [Terminal-Geek/RadioBeere#1]
Hi there,
do you have got screenshots of RadioBeere? The project sounds very interesting. Thanks.

**Comment by Terminal-Geek** [comment]
Hi Udo,

yes, I do. See the full documentation (in german) with screenshots on my website:

http://www.tobias-gehle.de/radiobeere-livestream-recorder-audioserver-raspberry-pi/

Regards
Tobias
